### ISSUE TITLE
List of test set images

### ISSUE THREAD

**Issue by SatSonu** [mahmoudnafifi/Exposure_Correction#1]
Hello,
i'm a student and i read your paper, i'm trying to create the dataset and i would like to ask you if it is possible to have the list of images of the test set.
Thanks!

**Comment by mahmoudnafifi** [comment]
It will be available soon. I can't predict a specific date, but we will work on that very soon.

**Comment by mahmoudnafifi** [comment]
The dataset is now available with all testing images and their ground truth images.
