### ISSUE TITLE
How do you resize images for evaluation and testing ?

### ISSUE THREAD

**Issue by elientumba2019** [mahmoudnafifi/Exposure_Correction#11]
Hello Dear Author.

I have noticed that most of the images in the validation and test set are not exactly powers of 2, Therefore,
when downsampling them in Unets like architectures the dimensions won't exactly match in the encoder and decoder when doing skip connections. This is not an issue when it comes to training since patches can be extracted. However, when evaluating or testing on full-size images from the dataset you proposed it becomes an issue.

My questions are the following : 

1. How do you resize them (the images) before performing your evaluation and testing?
2. Or, do you extract patches from them? if so what size of the patch and what location?

Thank you .

**Comment by mahmoudnafifi** [comment]
Hi @elientumba2019,
Thank you for your question. You can resize these images before feeding them into your network and then resize them back to get the original size. Of course, you may think of applying minimal resizing to match the requirement of your network to avoid losing much information before processing. 

In the paper, we use patches for training/validation. For testing, we use the [bilateral guided upsampling](https://dl.acm.org/doi/10.1145/2980179.2982423) to apply the enhancement to a resized version of the image then transfer it to the full-size image. 

I hope this helps!
