### ISSUE TITLE
[Feature Requested] Will a PyTorch version of the code be available?

### ISSUE THREAD

**Issue by CaptainEven** [mahmoudnafifi/Exposure_Correction#15]
I noticed the code is based on Matlab, which is very expensive...
It's greatly appreciated if a Pytorch(free to use) version of the code provide!

**Comment by mahmoudnafifi** [comment]
Regrettably, I cannot guess when I could provide a PyTorch version and it's possible that it won't ever be released. You can create a PR to contribute. Contributions are always welcomed!
