### ISSUE TITLE
Pyramid loss

### ISSUE THREAD

**Issue by RostyslavBryiovskyi** [mahmoudnafifi/Exposure_Correction#19]
Hello, @mahmoudnafifi ! Great work, thank you for that.
Do you use pyramid loss in this matlab implementation ? Because I haven`t noticed

**Comment by mahmoudnafifi** [comment]
It is used. The pyramid layers are packed and it is applied once. See this function:
https://github.com/mahmoudnafifi/Exposure_Correction/blob/master/src/packingGLayer.m
