### ISSUE TITLE
Dataset release

### ISSUE THREAD

**Issue by ghost** [mahmoudnafifi/Exposure_Correction#2]
When are you going to release the dataset? -Thanks

**Comment by YinengXiong** [comment]
When are you going to release the dataset? -Thanks

**Comment by mahmoudnafifi** [comment]
It will be available soon. I can't predict a specific date, but we will work on that very soon.

**Comment by mahmoudnafifi** [comment]
It is available now.

**Comment by mahmoudnafifi** [comment]
It is available now.
