### ISSUE TITLE
Training code 

### ISSUE THREAD

**Issue by Li-Chongyi** [mahmoudnafifi/Exposure_Correction#23]
Hi @mahmoudnafifi 

Thanks for the excellent work on exposure correction! 

I tried to retrain your code using my data. After training, I obtained three generator models and three discriminator models. 
I wonder which model can be used to generate the final results. I have tried to replace the 'model' in the demo_image_directory.m with 'model_128', 'model_256', and 'model_512'. But I cannot obtain the correct results. 

Could you please give me some advice to generate the correct results using the retrained models? Thanks！

![thumbnail_Screenshot](https://user-images.githubusercontent.com/34166801/177033645-5b33313f-2ae2-46e8-9668-936894bd505a.png)

**Comment by mahmoudnafifi** [comment]
Hi @Li-Chongyi, thanks for your interest in the work. The final model should be model_512. I am surprised that you couldn't obtain the same results when replacing the provided model with model_512. Just out of curiosity, did you change any parameters in the training code before training?

**Comment by Li-Chongyi** [comment]
Hi @mahmoudnafifi Thanks for the reply. I may change the training code. I will double-check my training code and get back to update the progress.

**Comment by Li-Chongyi** [comment]
The training code works. Thanks for the reply.
