### ISSUE TITLE
When are you going to release the dataset? -Thanks

### ISSUE THREAD

**Issue by 906527105** [mahmoudnafifi/Exposure_Correction#4]
When are you going to release the dataset? -Thanks

**Comment by YinengXiong** [comment]
Five months passed

**Comment by 906527105** [comment]
maybe，forever

**Comment by mahmoudnafifi** [comment]
The dataset will be available very soon. We just wait to get a permission for sharing. I will post here once the download links become available in the readme file.

**Comment by tuvovan** [comment]
any updates?

**Comment by YinengXiong** [comment]
any updates?

**Comment by jzakirov** [comment]
Hi @mahmoudnafifi 
I'm a MSc student interested in your work. I'd like to replicate your results and compare different methods using the dataset you collected.
Can you estimate when the dataset is going to be released?

**Comment by mahmoudnafifi** [comment]
Hi @zakajd 
Thanks for your interest. I know it takes a long time, but most likely it will be available by the end of this month.

**Comment by jzakirov** [comment]
Thanks for the fast response!
I understand that publishing data requires lot's of approvals, just wanted to know the timeline 👍

**Comment by elientumba2019** [comment]
Hello, in your paper you mentioned the adobe camera raw SDK. I am trying to render the MIT5k dataset however Adobe  [APIs](https://console.adobe.io/servicesandapis) and services do not seem to have an SDK that goes by the name of **Camera raw SDK** in the list of APIs. maybe it comes under another name.  Could your please point me toward the SDK you used? or provide the code or method used to render the raw files?
I found at camera raw plugin [here](https://helpx.adobe.com/hk_en/camera-raw/kb/camera-raw-plug-in-installer.html#),  I dont know if it is the one you used.
Thank you

**Comment by elientumba2019** [comment]
@mahmoudnafifi

**Comment by mortium91** [comment]
Looking forward to be working with the dataset!

**Comment by mahmoudnafifi** [comment]
I just released the download links in the readme file.
